# Generated by Django 4.0b1 on 2021-11-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('support_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Вопрос пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('ticket', models.ForeignKey(blank=True,
                                             null=True,
                                             on_delete=django.db.models.deletion.CASCADE,
                                             related_name='user_ask',
                                             to='support_system.ticket'
                                             )
                 ),
            ],
            options={
                'verbose_name': 'Вопрос пользователя',
                'verbose_name_plural': 'Пользовательские вопросы',
                'db_table': 'user_question',
            },
        ),
    ]
