version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: support_web
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - support_service/.env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: my_db
    env_file:
      - support_service/.env

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - '8080:8080'

