# Generated by Django 4.0a1 on 2021-10-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Статус тикета')),
            ],
            options={
                'verbose_name': ' Статус | StatusTicket',
                'verbose_name_plural': 'Статусы | StatusTicket',
                'db_table': 'status_ticket',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Название нового тикета')),
                ('content', models.TextField(verbose_name='Содержание нового тикета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status_ticket', models.CharField(choices=[('1', 'Тикет заморожен'), ('2', 'Тикет решен'), ('3', 'Тикет не решен')], default='3', max_length=2, verbose_name='Статус тикета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': ' Тикет | Ticket',
                'verbose_name_plural': ' Тикеты | Ticket',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='SupportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_answer', to='support_system.ticket')),
            ],
            options={
                'verbose_name': ' Ответ поддержки | Ticket',
                'verbose_name_plural': ' Ответы поддержки | Ticket',
                'db_table': 'support_answer',
            },
        ),
    ]
