# Generated by Django 4.0b1 on 2021-11-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('title', models.CharField(
                    blank=True,
                    default='Без названия',
                    max_length=125,
                    verbose_name='Название тикета'
                )),
                ('content', models.TextField(verbose_name='Содержание тикета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status_ticket', models.CharField(
                    choices=[('1', 'Тикет заморожен'),
                             ('2', 'Тикет решен'),
                             ('3', 'Тикет не решен')],
                    default='3',
                    max_length=2,
                    verbose_name='Статус тикета'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='auth.user',
                    verbose_name='Пользователь'
                )),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'db_table': 'ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='support_answer', to='support_system.ticket',
                                             verbose_name='Тикет')),
            ],
            options={
                'verbose_name': ' Ответ саппорта',
                'verbose_name_plural': ' Ответы саппорта',
                'db_table': 'support_answer',
            },
        ),
    ]
