# Generated by Django 4.0b1 on 2021-10-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_system', '0002_alter_statusticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportanswer',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_answer', to='support_system.ticket', verbose_name='Тикет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, default='Без названия', max_length=125, verbose_name='Название тикета'),
        ),
    ]
